"""Project-local device registry and loaders.

Devices are stored under <repo>/data/<model_name>/wires/<wire_name>/tool.py
as generated by the UI wizard. This package provides a stable API to list
and load those devices without editing upstream stEVE code.
"""

from .registry import list_devices, load_device_class, make_device

__all__ = [
    "list_devices",
    "load_device_class",
    "make_device",
]
