"""Project-local device registry and loaders.

Devices are stored under dev/gw_tool_recommender/data/<tool_name>/tool.py
as generated by the UI wizard. This package provides a stable API to
list and load those devices without editing third_party code.
"""

from .registry import list_devices, load_device_class, make_device

__all__ = ["list_devices", "load_device_class", "make_device"]

